ソースコードの行数を警告するルール作成
Techpit-Market/curriculum-textlint pull request #10
Opened 2022-03-17 00:56 UTC by 44x1carbon

2022-04-04 14:44 UTC, moja0316 requested changes
以下コメントの確認をお願いします。
また、今回コードブロック内のコードの長さを10行に設定した根拠は聞きたいです（これは定例で揉む話かもしれないけど）

2022-04-04 14:44 UTC, moja0316 commented on textlint-rule-preset-techpit-host-guide/src/index.js
> +    }
ここで「`limitLineNum`を10に設定したい」意思は感じるけど、実際は13行でチェックを引っ掛けなかったので正しく機能していないと思われます。

2022-06-12 16:24 UTC, 44x1carbon commented on textlint-rule-preset-techpit-host-guide/src/index.js
> +    }
オプションで設定できるようにしようと思ってたけど執筆者側で変えれるとまずいと気づいたので15行に固定しました。

15行てのは以前の定例で話がでて15行ぐらいじゃないかなという話が出てた、ここは実際にかけてみて調整でいいかなと思っている

2022-06-16 17:42 UTC, moja0316 approved these changes
よいとおもいますー

2022-06-16 17:42 UTC, merged