ファイルパスが設定されているか確認するルールを追加
Techpit-Market/curriculum-textlint pull request #7
Opened 2022-03-16 00:13 UTC by 44x1carbon

2022-04-03 11:38 UTC, moja0316 requested changes
確認お願いします。

2022-04-03 11:38 UTC, moja0316 commented on textlint-rule-preset-techpit-host-guide/test/codeblock-empty-filepath-test.js
> +        `.trim(),
![スクリーンショット 2022-04-03 20 36 54](https://user-images.githubusercontent.com/45286006/161426049-514762b1-6537-4210-bffc-d5c618de7cee.png)

Techpitの仕様が悪い気も若干するが、コロンなしで末尾`/`で終わるパターンはTechpit上でファイル名が表示されないので通すとまずいと思います。

2022-04-03 11:38 UTC, moja0316 commented on textlint-rule-preset-techpit-host-guide/test/codeblock-empty-filepath-test.js
> +        `.trim(),
個人的には言語名書かずにファイル名だけ書くパターンは弾いていいと思います

2022-06-12 16:24 UTC, 44x1carbon commented on textlint-rule-preset-techpit-host-guide/test/codeblock-empty-filepath-test.js
> +        `.trim(),
ファイル名だけパターンははぶきました〜

2022-06-16 17:39 UTC, moja0316 approved these changes
良いと思いますー

2022-06-16 17:40 UTC, merged